### ISSUE TITLE
Location not working

### ISSUE THREAD

**Issue by RevealedSoulEven** [rodit/SnapMod#104]
The location hack isn't working even after adding latitude and longitude too. I know it's clearly written there that you're not sure that it will work, but still, if it's useless you should remove this. Not being rude, but yea many many thanks for such a great mod and updates❤️

**Comment by Magna-Graecia** [comment]
Keep in mind that just because it doesn't work for you doesn't mean it doesn't work for anyone else. I've had numerous features that didn't work for me but worked for others, so it would have been unreasonable for me to request rodit to remove them solely on that basis.

Anyway, I'd highly recommend using "Fake GPS Location Spoofer" if spoofing your location is what you're trying to accomplish. Not only is it a whole lot easier, but you have so much more control and options. You can set things like altitude, movement and speed, staying in one location but moving around slightly so it looks real, creating a route with different options, and so much more. It makes needing a location spoofing option in SnapMod completely unnecessary.

**Comment by rodit** [comment]
Yes, in this case, I agree - this feature probably doesn't work (I spent about 10 minutes on it and haven't tested it, the method it uses also doesn't make much sense). I will most likely remove it entirely in a future update.

**Comment by RevealedSoulEven** [comment]
Yea anyways, it's ok
