### ISSUE TITLE
Audio notes not downloading

### ISSUE THREAD

**Issue by iRashiD-AE** [rodit/SnapMod#118]
The latest update is amazing, but there are some bugs.

![Screenshot_20220514-223555_SnapMod~2](https://user-images.githubusercontent.com/52901789/168444507-7a5157fe-336f-47a8-8d58-931126465e6f.png)

When this option is enabled, I can not save anything, knowing that it was working in version 1.6.0 and lower, and when turned off I can save, but I cannot save voice notes and snapmap images ، sry for my English 🙏

**Comment by Magna-Graecia** [comment]
Can confirm there are some saving issues now. Unlike iRashiD-AE, I'm still able to save snaps, chat photos/videos, etc whether "Use Android Download Manager" is enabled or not, but I can no longer save voice notes. Also, you had fixed the saving directly from SnapMap issue in a previous update (whether intentionally or not), but now it's back to doing what it did before. It still downloads a file, but it's a tiny unplayable 1.32 KB file. Sending the video from SnapMap to myself in a chat, then saving from there, still works though. This is how I prefer to do it anyway because after the saving directly from SnapMap issue was fixed, I noticed a large difference in both file size and video quality between saving the same video directly from SnapMap, or sending it to myself in a chat and THEN saving. Sending it to myself and saving resulted in a much larger file and much better video quality. You may remember that I noted this to you just for informational purposes in a previous comment after whatever update fixed the saving directly from SnapMap issue.

**Comment by iRashiD-AE** [comment]
> Can confirm there are some saving issues now. Unlike iRashiD-AE, I'm still able to save snaps, chat photos/videos, etc whether "Use Android Download Manager" is enabled or not, but I can no longer save voice notes. Also, you had fixed the saving directly from SnapMap issue in a previous update (whether intentionally or not), but now it's back to doing what it did before. It still downloads a file, but it's a tiny unplayable 1.32 KB file. Sending the video from SnapMap to myself in a chat, then saving from there, still works though. This is how I prefer to do it anyway because after the saving directly from SnapMap issue was fixed, I noticed a large difference in both file size and video quality between saving the same video directly from SnapMap, or sending it to myself in a chat and THEN saving. Sending it to myself and saving resulted in a much larger file and much better video quality. You may remember that I noted this to you just for informational purposes in a previous comment after whatever update fixed the saving directly from SnapMap issue.
> 
> EDIT: Here is the issue where I commented that saving directly from SnapMap now works: #89 .. It's in the 4th comment down.
> 
> Also, to comment on the rest of the update. The "disable snap splitting" feature works beautifully, but I can't comment on the feature that forces the new audio note UI since I already have it. However, are people still able to press and hold on an audio note to get the "Set Playback Speed" option when forcing the new UI? Because it still doesn't show for me. Not sure if it's supposed to still not show. What is the max speed that you can set with that option? If it's 2x then it doesn't really matter anyway, since 2x is the max you can do with the new audio note UI.

In fact, it was working perfectly, but after update 1.6.x I started having issues

**Comment by rodit** [comment]
Audio notes probably don't save due to the new audio note system. Also, I did not fix the snap map stories. some of them are actual videos, some are mpds (the small 'unplayable' files). If they are mpds there's nothing I can do to change that.

In regards to the audio note view, you can set the playback speed globally with snapmod, but I haven't yet made it possible to set the playback speed for the new audio note view. With SnapMods playback speed it can be set to anything.

I will fix the voice note saving soon (it's something I forgot to test when adding support for the latest Snapchat) but I will not fix snapmap downloading.

**Comment by rodit** [comment]
Also, what version of Android are you on?

**Comment by Magna-Graecia** [comment]
Oh that makes sense then. Either way, it's really a non-issue for me because I was saving SnapMap stories by sending them through a chat to myself anyway, as even for the ones that work to save directly from SnapMap, the files are smaller and lower quality from there (compressed or something). I'd rather have the larger, higher quality version, so saving for these hasn't changed for me haha.

Oh ya! I forgot that there's a global option for playback speed. Anyway, I just tried it but it didn't work. I tried multiple speeds (2x, 5x, etc). The only thing that works is using the built-in toggle by Snapchat, so I'm guessing something may have changed for those that are in the new testing group with the new features. I think your idea of increasing the range of options on the built-in speed toggle is right on the money. That's the best method of approach if it's easy for you to do.

Thanks for letting me know about the "Delete Original Message" option. It definitely would have been hilarious to use just to troll your friends haha. Like "bro, what are you talking about you? You never sent me anything....." and then they scramble looking for the disappeared message, scratching their head, beginning to question what is real and what is not in this world 😂

I'm pretty sure your question regarding Android version is directed towards iRashiD-AE, as I believe you're already aware of mine, but mine is 8.1.0 just in case haha

**Comment by iRashiD-AE** [comment]
> Also, what version of Android are you on?

12 , custom rom

**Comment by rodit** [comment]
> 12 , custom rom

Have you changed the download paths for stories? Also, do you have multiple users setup on the phone/any kind of DualApp setup? It's very odd that the download manager doesn't work on Android 12.

**Comment by iRashiD-AE** [comment]
> > 12 , custom rom
> 
> Have you changed the download paths for stories? Also, do you have multiple users setup on the phone/any kind of DualApp setup? It's very odd that the download manager doesn't work on Android 12.

I didn't change path and I don't use multiple users , it was working perfectly.

**Comment by rodit** [comment]
I have fixed audio note downloading for the new audio note view in v1.6.4

I'm not sure why it would suddenly stop working - please try the latest version and mention here if you still can't download anything.

Please make sure you kill and reopen Snapchat twice after updating.

**Comment by Magna-Graecia** [comment]
@rodit Can confirm audio note downloading is now working. What was wrong with auto saving? I was looking at the release notes. I personally didn't notice anything wrong with it before. Did I miss something? It's still working as before though, so that's good haha. Sending videos > 10 seconds was failing when trying to send to multiple recipients? I know I sent >10s videos to my other account and my story in 1 go (if that counts as another recipient haha), and it was fine. Although I'm not 100% sure if I did that after the most recent update, so maybe something was broke with that and I hadn't noticed before you updated.

The only benefit to the override snap timer feature was that it caused snaps sent from gallery by just tapping on them and sending to be sent as "unlimited view" snaps. So they would just repeat in the case of a video, or stay up until the recipient closed them in the case of a photo. I assumed this was because I had the timer option set to 0 in SnapMod, which was default. I assumed 0 meant unlimited. I never tried setting a different number, so I wouldn't know if that worked. The only thing I tried was deleting a number from the option entirely and just leaving it blank, but that broke sending gallery as snaps haha, so I put it back to 0. The reason I deleted the number was because having it at 0 caused the timer bubble to show on photos, but it was just empty like it had run out and would stay in the image permanently. I figured keeping the option blank instead of having a number would make it unlimited without the bubble showing, but that didn't work haha. So the only downside to sending by way of just tapping on a photo/video in gallery is that the timer is automatically set to a few seconds for photos now, or whatever length a video you're sending is, then they close. Not a big issue since you can just press and hold to load them into the camera window and set your options there, then send. Or share from gallery, set options, and once again send.

**Comment by rodit** [comment]
There was nothing 'wrong' with auto-saving in a breaking sense, it just would have occasionally shown an error message in xpsoed logs.

The override snap timer didn't actually change anything I'm pretty sure.

**Comment by Magna-Graecia** [comment]
@rodit Oh ok. That makes sense.

I can't comment on if it did or not, since I didn't try it. I just left it at the default "0", which made it unlimited, but would show the empty timer bubble on photos. Now there's a timer of a few seconds when simply tapping on a photo in gallery drawer and sending. Videos sent the same way play for the duration of the video and then close (no repeating).
