### ISSUE TITLE
Gallery Snaps Time Limit

### ISSUE THREAD

**Issue by tarek133** [rodit/SnapMod#122]
So whatever seconds I try to set for that option, it just won't work. The default option is "0". What is that supposed to do?
I noticed when you send a snap from memories (tap on memory and just hit the send button, then select whoever you want to send to) the snap always has a timer on it. I think it's 3 seconds. But when you send a snap from the in-chat gallery drawer or from your phone's gallery, there's never a timer and it's unlimited.

**Comment by rodit** [comment]
I have removed this feature as I don't think i'll be able to get it to work. You can modify the timer for gallery snaps in the edit screen (hold down on the image in the in-chat gallery drawer).

**Comment by Magna-Graecia** [comment]
@tarek133 Just FYI, if you're sending from the "Snaps" section within memories, those snaps get sent with whatever settings you originally saved them as. So for example if the duration was set to 3 seconds when you tapped the "save to memories" button in the bottom left of the screen, then when you send that snap from memories with "Send Gallery as Snaps" enabled, it will go as a live snap with 3 seconds duration.

By the way, are you able to send videos longer than 11 seconds from memories now? It's still not working for me. Nothing happens when trying it. No sent or error notifications. Just nothing.

**Comment by tarek133** [comment]
> @tarek133 Just FYI, if you're sending from the "Snaps" section within memories, those snaps get sent with whatever settings you originally saved them as. So for example if the duration was set to 3 seconds when you tapped the "save to memories" button in the bottom left of the screen, then when you send that snap from memories with "Send Gallery as Snaps" enabled, it will go as a live snap with 3 seconds duration.
> 
> By the way, are you able to send videos longer than 11 seconds from memories now? It's still not working for me. Nothing happens when trying it. No sent or error notifications. Just nothing.

Ahhh that makes sense now. Thanks for explaining!
And no, sending videos longer than 11 seconds from the memories tab still doesn't work for me either

**Comment by Magna-Graecia** [comment]
@tarek133 You're welcome!

Oh ok, so it's not just me then. Maybe rodit intends on fixing it, or maybe not. It's not that big of a deal either way. It's just slightly inconvenient when using my method to post >11 second videos to story without the "from camera roll" tag AND with a custom timestamp since the method involves saving to memories and sending from there. I can still do it, but I need to disable "Send Gallery as Snaps" first. I think it has something to do with the video restriction bypass not being applied to memories, sort of like before when it was applied to snaps sent from the gallery drawer within a chat, but not to snaps shared from gallery to Snapchat. Then rodit updated it to apply globally and fixed the "share from gallery" issue, but for whatever reason it's not applying to memories. Maybe he'll be able to apply it to that as well.

**Comment by tarek133** [comment]
> @tarek133 You're welcome!
> 
> Oh ok, so it's not just me then. Maybe rodit intends on fixing it, or maybe not. It's not that big of a deal either way. It's just slightly inconvenient when using my method to post >11 second videos to story without the "from camera roll" tag AND with a custom timestamp since the method involves saving to memories and sending from there. I can still do it, but I need to disable "Send Gallery as Snaps" first. I think it has something to do with the video restriction bypass not being applied to memories, sort of like before when it was applied to snaps sent from the gallery drawer within a chat, but not to snaps shared from gallery to Snapchat. Then rodit updated it to apply globally and fixed the "share from gallery" issue, but for whatever reason it's not applying to memories. Maybe he'll be able to apply it to that as well.

About the snap timer: Whenever I send a snap from the chat gallery drawer (one tap on it, not long pressing) the snap timer is set to 3-4 seconds on default. No matter what type of picture I send. It's also for pictures that I took with my phone's camera. Only when I long tap the picture in the chat gallery drawer and load it into the sending-interface it sends as unlimited snap with no timer on it. Do you have any idea why's that?

**Comment by Magna-Graecia** [comment]
@tarek133 Yes, that's because rodit removed the override snap timer feature. It was set to 0 by default, which made all snaps sent from the in-chat gallery drawer unlimited if you simply tapped on it to checkmark it and pressed send, but it would show an empty snap timer bubble on the photo for the receiver. Since rodit removed this feature, they now get sent with a default timer of 3-4 seconds like you said. If you press and hold on them to load them into the camera edit window, then they get sent with whatever timer you set there. It's logical. You probably have it set to unlimited, and that's why they're getting sent as unlimited. If you change it from unlimited to 3 seconds, you will see it will be 3 seconds there as well, etc.

**Comment by rodit** [comment]
Please could you open another issue about sending videos from memories as snaps - this is something I'd like to fix.

**Comment by Magna-Graecia** [comment]
@rodit Of course :)

Opening a new issue for it now. Just to be clear, sending videos from memories as snaps works fine if they're <11s long. Just not when they're >11s long. This is why I believed it was tied to the video restriction bypass not applying, but you would know more about that than I do.

By the way, just had a quick question on the latest update. I saw your note under "Show Media Previews" that states the entire media needs to be downloaded for it to work. Is the media getting downloaded and saved anywhere on our devices where we need to go clear them so they don't keep filling up space? Or do they get downloaded but not saved? I don't care about data consumption, just storage potentially filling up.

**Comment by rodit** [comment]
@Magna-Graecia the media gets deleted after the preview is generated - the media is downloaded temporarily to Snapchats cache folder so if for some reason it doesn't get deleted, clearing Snapchats cache in the settings will delete it.

I'm gonna open an issue about the save to camera roll button so I don't forgot about it haha.

**Comment by Magna-Graecia** [comment]
@rodit Awesome! This is how I thought it probably worked since I didn't see any new images being downloaded to storage, but it's great to know! Thank you!

Haha alright sounds good. I left you a nice little new comment on there that's reminiscent in tone with many of the "requests" being posted here lately, at least in my opinion 😂
