### ISSUE TITLE
60 seconds video Restriction even after turning on bypass video length restrictions

### ISSUE THREAD

**Issue by RevealedSoulEven** [rodit/SnapMod#127]
I've turned on the bypass video restrictions feature.

The thing is that it bypasses 11 seconds restriction but still the 60 seconds restriction is coming up there.

Making it quite clear, it's coming only where I select from camera roll near the snap camera option. But while sending videos from the in-chat camera roll option, it works fine.

And even a 2 min video is being sent as a single snap when I'm sending from in-chat camera roll, even I don't need it. But from the camera roll option near the snap camera(homepage) it splits into parts (which I need it to be)

![Screenshot_2022-05-16-11-59-53-524_com snapchat android](https://user-images.githubusercontent.com/49313374/168533166-a2451cda-f98c-4ebd-a446-ff9e3012682a.jpg)

This is the error which is showing in homepage camera roll

**Comment by rodit** [comment]
If you want the snaps to be split, disable the 'no snap splitting' option and send it through the edits screen (i.e. hold down on the video in the in chat gallery, or share it through an external gallery app).

I will have a look at removing the 60 second limit from the in app camera roll though for convenience.

**Comment by RevealedSoulEven** [comment]
Yeaa sure. I already knew that I can control that snap splitting part by holding the video and sending snap from the edit screen. But I just reminded in case you weren't aware of it.
Anyways hope you'll fix that 60 seconds restriction soon.

**Comment by Magna-Graecia** [comment]
This is a bit of a non-issue if I may say so myself. Adding this for convenience wouldn't even be much of a convenience because why in the world would you ever want to use the edit screen camera roll to find a photo/video to send? Everything gets ordered there by "recent date", so older stuff means you need to endlessly scroll. This is partly why rodit added the ability to bypass the video length restriction when sharing from gallery to Snapchat. You have so much more control over organizing and filtering for files when using your own file explorer and sharing to Snapchat from there, then sending.

The only benefit to using the in-chat gallery drawer (not the edits screen one), is that loading a photo/video from there by longpressing on it allows you to upload to story without any "from camera roll" tags when this is needed. If you try to do this with a photo/video shared from gallery to Snapchat, you will get a "from camera roll" tag.

What would truly be of benefit is we can get a fix for sending videos longer than 11 seconds directly from the memories window without having to disable "Send Gallery as Snaps" each time we wanted to do it. This allows us to use my method posted in https://github.com/rodit/SnapMod/discussions/105 to post stories with a custom timestamp AND no "from camera roll" tags.

**Comment by RevealedSoulEven** [comment]
Yeaaa. Anyways it works btw. That 60 seconds restriction is useless though
