### ISSUE TITLE
Save to camera roll not appearing for snaps/audio notes etc.

### ISSUE THREAD

**Issue by rodit** [rodit/SnapMod#141]
This is a reminder to myself to fix this, and also to stop anyone from posting about the same issue.

**Comment by AroPix** [comment]
Is meant with this that the snaps are not saving? As for me the Movies\SnapMod is empty when i have autosave enabled.

**Comment by Magna-Graecia** [comment]
Yes I demand that you fix this immediately for the zero money that I'm paying you REEEEEEEEEEEEEEEEEEEEE 😂👅

**Comment by rodit** [comment]
Fixed in 1.7.2

**Comment by Magna-Graecia** [comment]
> Fixed in 1.7.2

Aw man, it looks like deleting the filters for Hide Save/Unsave Chats now causes messages to be auto-saved when both Auto-Save Messages and Stealth Mode are enabled. It looks like it was the Hide Save/Unsave Chats in the xml that was enabling once Stealth Mode was enabled, and this prevented Auto-Save Messages from working when stealth viewing a chat. I was going on about how I liked that haha. Now since it was removed from xml, it's no longer part of Stealth Mode and so it no longer activates and interferes with Auto-Save Messages when Stealth Mode is enabled, so when stealth viewing a chat with Auto-Save Messages enabled they get saved and can give your stealth away. We have to be mindful of the auto-save option now and keep toggling it on and off if we want stealth to be effective.
