### ISSUE TITLE
Saving Snaps doesn't save the caption, only when saved in chat

### ISSUE THREAD

**Issue by tarek133** [rodit/SnapMod#155]
So what I noticed is, that when you save snaps while swiping up/long pressing within the snap:
![Screenshot_20220523-160427](https://user-images.githubusercontent.com/12681440/169837446-7186559e-9985-4df3-89f7-852f416d727f.png)

it won't save the caption. Only the image itself gets saved. 
Though, when you save snaps from within the chat to camera roll, the caption gets saved along with the snap.

I think it might be a good thing, to have an option whether you want to save with the caption, or without.

**Comment by rodit** [comment]
Yes, unfortunately it's not very easy to get the edits such as the caption to save with the snap generally (without going through Snapchat's export system) so I do not really plan on changing this unless I stumble across an easy way to do it.

**Comment by Magna-Graecia** [comment]
You're referring specifically to video snaps, right? Image snaps get saved with all edits on my end no matter the way you save them. Video snaps get saved as you stated, and I personally like it that way because we have a choice to save with edits or without. I get that having a button maybe makes it slightly more convenient (like 'Save with edits' and 'Save without edits'), but it's not really necessary in my opinion, especially when considering the complexity and work that might be involved for rodit to make it happen.

Right now you can just save within the snap to get it without edits, or save using the in-chat context menu to get it with them. It's BARELY less convenient, and the best part is that you get a choice. On SnapFreedom we didn't get that choice. Just my 2 cents.
