### ISSUE TITLE
Sending from gallery

### ISSUE THREAD

**Issue by jackuzug3018** [rodit/SnapMod#17]
This feature works well but could be improved greatly by disabling it on gallery photos sent via the snapchat app itself. Rather than having to disable the feature in Snapmod, send a photo to chat from gallery via snapchat chat then enabling the feature again.

**Comment by tarek133** [comment]
+1

**Comment by rodit** [comment]
I agree, it is quite annoying when you want to send gallery pics normally. The issue is it's very difficult to consistently find a good place to intercept the picture sending in a way that allows gallery snaps to be sent as live snaps. The reliable place I have found to intercept it is quite far down the line, at which point it's quite difficult to tell where the image came from (whether it was from a share from another app, or the gallery in Snapchat). I will continue to look into better ways of doing this but, for now, it probably won't be changed.

**Comment by Lucky-069** [comment]
It would be nice if there could be instructions on how this feature can be implemented I tried toggling through settings but it simply sends as chat
