### ISSUE TITLE
Error while send snap from gallery 

### ISSUE THREAD

**Issue by Lucky-069** [rodit/SnapMod#20]
I have tried toggling settings and send the pictures or videos via gallery within snap aswell as from the third-party gallery app but the pictures won't send as snap and simply get send to the chat. Would someone explain how to make it work.

**Comment by Lucky056** [comment]
Also it seems that my chats go blank whenever I try to use hide Bitmoji enter or exit

**Comment by jackuzug3018** [comment]
Post which settings you have selected.

**Comment by Lucky056** [comment]
@rodit what about send snaps through gallery they don't seem to work for me. Although it works through a different spoofer app from magicsnap repo

**Comment by Lucky056** [comment]
Or it would be great if you could simply add instructions in Readme or add a screen recording. Thank you for the app tho! ♥️ Love it

**Comment by rodit** [comment]
Maybe try disabling 'Override Gallery Snap Type'

**Comment by Lucky056** [comment]
@rodit thanks it works now. It would be good if you could add this in Readme so other users don't face this issue. Also this is completely irrelevant but is there any way that dark mode can be added through the module or would it be something very different. Because I hate light mode and idek why snap doesn't have a dark mode on Android yet

**Comment by Lucky056** [comment]
@rodit you can use swift black or swift installer tho. It's working well on snapchat and offers amoled black background!
