### ISSUE TITLE
[Suggestion] fit to screen

### ISSUE THREAD

**Issue by jackuzug3018** [rodit/SnapMod#44]
Fit images and videos from gallery to screen when sending from gallery.

**Comment by rodit** [comment]
What do you mean by this?

**Comment by jkooper32** [comment]
I think he means for the image being uploaded from the gallery to fit the entire screen of the device being used. The image itself has to detect the device aspect ratio and expand the image to match the aspect ratio of the device automatically. Back when using snapTools I used to send images from the gallery and depending on image rotation or wherever I got the image from, people could tell that there was something off because even though the image was being sent as a live snapchat image - the size of it or orientation was off balance. 

When taking pics from the snapchat app itself I think it automatically manipulates the image to fit the correct screen size of the device being used

**Comment by rodit** [comment]
I'd need to see an example of how the image doesn't fit to screen to fix it (i.e. a screenshot of it from the receiver's end) + the original image being sent.

**Comment by jackuzug3018** [comment]
A lot of other snapchat mods had this feature in their app, snapfreedom being one. Snapchat live pictures are supposed to cover the whole screen of your device, whereas pictures from gallery don't necessarily do that (many photos from camera are taken in 3:4 rather than full screen). Usually "fit to screen" will modify the image so that it fits to the screen like a snapchat direct one.

I think fill is the correct term someone correct me if I am wrong: Fill - Fill will always fill the bounding box completely with the image. The image will extend pass the bounding box to maintain a complete fill. The image's aspect ratio is preserved.

**Comment by rodit** [comment]
What so it's acceptable for some of the image to be cropped off the screen?

**Comment by jackuzug3018** [comment]
Some of it has to be cropped off the screen otherwise the image will be wrong I believe, stretched one way or another too much. It is usually not much of an issue especially with current phones taking high quality photographs. The important point is that ratio is maintained (realistic) and screen is filled.

**Comment by Magna-Graecia** [comment]
If added, I think this should be a built-in cropping tool like SnapFreedom had. If it just crops and fits the image to the screen on its own, then it's going to look like crap. I would rather crop photos to the proper ratio on my PC, or even with an app, to have them ready to send through snapchat beforehand than to have SnapMod crop it on its own. It's going to look like crap if not cropped properly. I would prefer to be able to choose to have it sent live as is like we currently have, or to send it to "SnapMod cropping tool" before going on to be sent live.
