### ISSUE TITLE
Gallery snaps to story posting issue

### ISSUE THREAD

**Issue by thracianx** [rodit/SnapMod#50]
![Snapchat-306578129](https://user-images.githubusercontent.com/103907028/164116902-29fda5a8-30db-4ba9-b5df-1e151b52ebfe.jpg)
Sending gallery snaps to story(public or private) puts a 'from camera roll' when anyone views it.

**Comment by Magna-Graecia** [comment]
Pro tip to get gallery snaps sent to story to not show "from camera roll":

Just open a chat, open the gallery drawer, and then press and hold on the photo/video you want to share. This will cause it to load into the camera window. From there, hit the "save/download" button in the bottom left-hand corner. This will add the photo/video to the snaps section of memories with a recording of the current date, time, and location. Close out of that snap, open the one in memories, and send it to your story, It now won't show "from camera roll".

You can also share the photo/video from gallery to snapchat to load it into the camera window instead of using the gallery drawer in a chat, but keep in mind that videos longer than 11 seconds won't load into snapchat this way. That has been my experience at least. I need to use the gallery drawer in chats for videos longer than 11 seconds. Also, make sure to add any filters to the photo/video before hitting the "save/download" button in the bottom left. Once you press that button, the photo/video will be saved to memories with all of the edits you made. If you try to add filters to the photo/video once it's in memories, you might not have access to same ones you normally do. It's buggy

**Comment by thracianx** [comment]
Can confirm the above memories method works but it's bit of a hassle if you got multiple snaps to upload, better than nothing though.

**Comment by Magna-Graecia** [comment]
> Can confirm the above memories method works but it's bit of a hassle if you got multiple snaps to upload, better than nothing though.

Ya but if you had multiple snaps to send, then you would still need to send them one by one anyway, so this is just one small extra step. Instead of adding from gallery and then sending straight away, you're adding from gallery, hitting the save/download button, THEN sending. It's just one small extra step that takes 2 seconds. You can also add each one to memories from gallery using this method, then when you have them all in there you can send them all at once by holding on one to get the checkmark and checking all that you wanna send. Boom, done.

**Comment by Magna-Graecia** [comment]
@thracianx Hey, just an update on this. I was doing some testing today, and I found out that you do NOT need to load a photo/video into the camera window, then save to memories, then send from there for it to not show "from camera roll." All you need to do is go to the gallery drawer in a chat, press and hold on a photo/video so that it loads into the camera window, and send from there. You will see that it does not say "from camera roll".

Don't try to SHARE a photo/video from gallery to snapchat because this WILL cause a "from camera roll" tag to show. You have to do it the way stated above. Also, if you try to press and hold on a video longer than 10 seconds to load it into the camera window, you will get an error message saying "Videos longer than 10 seconds can't be edited." What you need to do is go to SnapMod settings and make sure "Bypass Video Length Restrictions" is enabled. Also, make sure you close snapchat and refresh it once or twice after enabling this feature just to make sure it enables fine.
