### ISSUE TITLE
"Save" function leaves blurry text and emoji layers.

### ISSUE THREAD

**Issue by Kyron1324** [rodit/SnapMod#61]
So the save snap functions works well aswell as the save to cameraroll function. But with the save function it saves a snap and removes emojis and letters but leaves a blurry after effect behind them. Can this be fixed to just remove both the emojis/letters + blurry effect so it's a plain snap

**Comment by Kyron1324** [comment]
![Picsart_22-04-26_00-33-35-168](https://user-images.githubusercontent.com/92324266/165221794-7973bf98-693e-4e9d-888a-bfd72d005f66.jpg)
Some context if i'm confusing.

**Comment by Magna-Graecia** [comment]
Can confirm. It happens when stickers are added to a video snap, and only with video snaps, not photos. Photos get saved with all edits intact (filters, stickers, text, etc) whether you use "save to camera roll" or just "save". Videos get saved with them intact when using "save to camera roll", but removed when using "save". When removed, stickers will leave the blurry after effect in the place where they were on the original video, Filters and text get removed with no after effects. This is how it worked with SnapFreedom as well, so it's not anything specifically wrong with SnapMod. It's just the way Snapchat embeds stickers to videos, so I'm not sure that anything can be done about it. Imagine if you took a photo, opened it in a photo editor, and used the pen tool to scribble out part of it in black color. Once that's saved, the scribble can't be removed without removing the part of the photo that was originally scribbled over because that part of the image has basically been replaced with new pixels. I believe this is also what's happening when stickers are added to video snaps. Some of the pixels are being replaced by the sticker, which is why you see pixelation in the place that it was removed from. Rodit can comment further on that

**Comment by rodit** [comment]
Yes, I am aware of this - for videos, any edits are stored separately. It probably is possible to recover them but rendering them on top and exporting the snap with all the edits in tact is likely quite a computationally expensive job and may even require ffmpeg or some other dependencies which I don't want to add to SnapMod. Although, video snaps with edits can be saved (i.e. from your memories) so there is probably a way to make Snapchat export with edits rather than going through Snapmod, but I don't see much point.

**Comment by Magna-Graecia** [comment]
> Yes, I am aware of this - for videos, any edits are stored separately. It probably is possible to recover them but rendering them on top and exporting the snap with all the edits in tact is likely quite a computationally expensive job and may even require ffmpeg or some other dependencies which I don't want to add to SnapMod. Although, video snaps with edits can be saved (i.e. from your memories) so there is probably a way to make Snapchat export with edits rather than going through Snapmod, but I don't see much point.

You can already save videos with all of the edits. You just go to "save to camera roll" from within chat and save from there. If you use "save" from the in-snap context menu, then it will get saved without the edits. In the case of a video that had a sticker as an edit, there will be pixelation in the place where the sticker was. That was OP's issue. He wants a way to be able to save videos without edits AND without the blurry pixelation appearing in the case of videos that had stickers. I don't think it;s possible though because I think stickers replace some of the original pixels in the video, which is why pixelation shows once the sticker is removed.

**Comment by Magna-Graecia** [comment]
> Oh yeah that definitely is not possible.

Ya I didn't think so either. Not a biggie to me, and the way we have it right now is really cool to be honest. On SnapFreedom there was no option to save videos with edits. You could only save with edits removed, and you would get a pixelation patch in the case of videos that had stickers. With SnapMod we have options. We can choose "save to camera roll" if we want the video with edits, or just "save" from the in-snap context menu to save it without edits. I'm loving this app more and more each day haha
