### ISSUE TITLE
V1.5.7 not working

### ISSUE THREAD

**Issue by eddywitkamp** [rodit/SnapMod#98]
Updated Snapmod to V1.5.7 
Snapchat 11.75.0.33 (build 84591)

Snapmod says the version is supported (mappings 84591)
Killed Snapchat numerous times.

But nothing works.

Was working fine before the update (V1.4.4)

**Comment by tarek133** [comment]
Try re-enabling the module in lsposed and reboot the device. Also try force stopping snap mod

**Comment by eddywitkamp** [comment]
Disabled and enabled the module, rebooted, killed SC en SnapMod, nothing works.

I know I am not on the latest supported version of SC, but that should not matter with the correct mappings right?

**Comment by eddywitkamp** [comment]
![image](https://user-images.githubusercontent.com/6422683/167497054-4516f49c-c6d1-49d8-889e-35ab3b5a35e5.png)
binding are there

**Comment by rodit** [comment]
If I add new features to SnapMod after a new version of Snapchat is released, those new features will (most likely) break SnapMod on older versions of Snapchat (some bindings in 84602.json will not be present in 84591.json). You have two choices, either update Snapchat or downgrade SnapMod. The latest version of SnapMod is only guaranteed to work with the latest supported version of Snapchat. This is not something I will probably ever change.

**Comment by eddywitkamp** [comment]
Well, then the Status of SnapMod should say "NOT supported" because showing it as supported is then not true.

Downgrade to my previous version worked fine.

**Comment by Magna-Graecia** [comment]
> Well, then the Status of SnapMod should say "NOT supported" because showing it as supported is then not true.
> 
> Downgrade to my previous version worked fine.

Why would you upgrade to the latest version of SnapMod if you planned on using an older version of Snapchat? Just stay on the version of SnapMod that corresponds to the version of Snapchat that you like. You also had bindings for 84602 installed, which is the correct bindings for the latest Snapchat, but not for the version that you were using. Since you had both the latest SnapMod and the latest bindings (84602) installed, naturally SnapMod may have been applying those settings that weren't made for your older version of Snapchat, so things became broken. It probably said it was supported because you did still have 84591 bindings installed, which correctly corresponded with your installed version of Snapchat, but the SnapMod apk itself was a later version with newer features that the 84591 bindings didn't even recognize. It was also maybe trying to use the 84602 bindings since you had them installed and the newer bindings maybe take precedence?

Either way, it's a bit of a non-issue. Keep in mind that these mods are intended for people with a certain level of Android OS technical ability and understanding, since naturally they require root, Xposed, etc, and most people at that level of understanding will know how to check if they have the correct versions, bindings, etc installed, regardless of what the installation status says. Just my 2 cents.

**Comment by jammyjay** [comment]
> Just my 2 cents.

Your two cents are spot on. There is a literal warning about this on the main Snapmod page read me.

**Comment by eddywitkamp** [comment]
> You also had bindings for 84602 installed, which is the correct bindings for the latest Snapchat, but not for the version that you were using.

This is something SnapMod asks for when opening it. There is a Download button that automatically downloads the latest bindings. 

I'm all for your comment about "certain level of understanding" but this part of SnapMod is confusing. 
a Cancel/Dismiss button on that update screen and a better Status reporting would make it less confusing.

**Comment by Magna-Graecia** [comment]
@eddywitkamp I forget if there's a cancel button when the download prompt comes up, but you can touch your screen outside of the prompt box and it will go away. No need to tap the Download button. One thing that I think would be beneficial is an option to disable "check for updates" so you don't continuously get that update prompt for those that want to remain on a specific version of SnapMod. @rodit Do you think it would be possible to add this option?
